#!/bin/bash
#
# wrapper for backupto-remote
# output to log and screen
#
# test dir / example file
#
# e.g. use w/ cron job like:
# 15 23 * * * cd /home/user/backup && ./backup-remote-test

DATE=$(date "+%Y-%m-%d_%H:%M:%S")

./backupto-remote \
    backup-conf/backup-test.conf \
    2>&1 | tee -a "backup-log/backup-remote-raspel-test_${DATE}.log"
