#!/bin/bash
#
# wrapper for backupto-remote
# output to log and screen
#
# test dir / example file
#
# e.g. use w/ cron job like:
# 15 23 * * * cd /home/user/backup && ./backup-remote-example

DATE=$(date "+%Y-%m-%d_%H:%M:%S")

./backupfrom-remote \
    backup-conf/backup-from-example.conf \
    2>&1 | tee -a "backup-log/backup-from-example-FULL_${DATE}.log"
