#!/bin/bash
#
# backup selected directories/files,
# config file as argument
#
# the config file shall contain the variables:
#
# SRC_PATH_ABS      absolute path to the files to backup, e.g. $HOME
# BACKUP_LIST       list of files/directories to backup,
#                   the list may contain # comments and empty lines
# EXCLUDES_LIST     list containing excludes, acc. to rsync --exclude-from
#
# DEST_PATH         destination path, can be relative
#
# ADD_RSYNC_OPTS    additional rsync options, e.g. used -R used for system backup
#

# includes
. common_f

check_config_arg "$1"
. "$1"
check_config_opts

create_dir "$DEST_PATH"

LOGFILE="$DEST_PATH"/daily.0.log
DATE=$(date "+%Y-%m-%d_%H:%M:%S")

echo "Backup start: $DATE" > "$LOGFILE"

# backup
rsync -av -i -r --numeric-ids \
    --files-from="$BACKUP_LIST" \
    --exclude-from="$EXCLUDES_LIST" \
    --delete \
    $ADD_RSYNC_OPTS \
    "$SRC_PATH_ABS" \
    "$DEST_PATH"/daily.0 >> "$LOGFILE" 2>&1

# exit on failure
if [[ "$?" -ne 0 ]]; then
    echo "A failure occured during rsync, exiting." >> "$LOGFILE"
    exit 1
fi

echo "Backup end." >> "$LOGFILE"
