#!/bin/bash
#
# backup list of directories/files to remote host,
# given config files as argument
#
# $1 remote settings
# $2 backup list
#
# using rsync (incremental)
# reference:
# - http://www.ibm.com/developerworks/aix/library/au-spunix_rsync/index.html#backup
# found on: https://wiki.archlinux.org/index.php/Backup_programs
#
# the config file shall contain the variables:
#
# SRC_PATH_ABS      absolute path to the files to backup, e.g. $HOME
#
# BACKUP_LIST       list of files/directories to backup,
#                   the list may contain # comments and empty lines
# BACKUP_PREFIX     backups will be in the form of PREFIX_DATE_TIME
#
# BACKUP_PATH       destination path, can be relative
# MOUNTPOINT        mountpoint within dest. path
#
# ADD_RSYNC_OPT     additional rsync options

# includes
. common_f

DATE=$(date "+%Y-%m-%d_%H:%M:%S")

echo "Backup start $DATE"

# check args
if [ ! $# -eq 2 ]; then
    echo "Config files expected as argument. Leaving."
    exit 1
fi

for c in "$1" "$2"; do
    check_config_arg "$c"
    source "$c"
done

# temporary preprocessed list file
TMP_LIST="/tmp/backup-${BACKUP_PREFIX}-remote-TMP.list"

preprocess_list

# incremental backup
# --link-dest: if relative path, it's relative to the destination dir (!)
rsync -av -r --numeric-ids --link-dest=../"$BACKUP_PREFIX"_last \
    $ADD_RSYNC_OPT \
    --files-from="$TMP_LIST" \
    "$SRC_PATH_ABS" \
    "$REMOTE_USER"@"$REMOTE_HOST":"$DEST_PATH"/"$BACKUP_PREFIX"_"$DATE"

# exit on failure
if [[ "$?" -ne 0 ]]; then exit 1; fi

# cleanup
rm "$TMP_LIST"

# relink last
# (rm needed or it goes into the link to create new one)
ssh "$REMOTE_USER"@"$REMOTE_HOST" rm "$DEST_PATH"/"${BACKUP_PREFIX}_last"
ssh "$REMOTE_USER"@"$REMOTE_HOST" ln -s "${BACKUP_PREFIX}_${DATE}" "$DEST_PATH"/"${BACKUP_PREFIX}_last"

echo "Backup end"
