#!/bin/bash (only for syntax highlight)
# common functions

check_config_arg() {
    # check for config file
    if [ "${1##*.}" != "conf" ]; then
        echo "A .conf file is expected. Leaving." >> "$LOGFILE"
        exit 1
    fi
    if [ ! -f "$1" ]; then
        echo "Config file not found. Leaving." >> "$LOGFILE"
        exit 1
    fi
    return
}

check_config_opts() {
    # check config options
    if [ ! -f "$BACKUP_LIST" ]; then
        echo "Backup list not found, leaving." >> "$LOGFILE"
        exit 1
    fi
    return
}

preprocess_list() {
    # preprocess list
    # (removing comments and empty lines)
    grep -v "^#\|^\s*$" "$BACKUP_LIST" > "$TMP_LIST"
    echo "Preprocessed list:" >> "$LOGFILE"
    cat "$TMP_LIST" >> "$LOGFILE"
    echo >> "$LOGFILE"
}

create_dir() {
    # create dir $1
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}
