#!/bin/bash
#
# efficiently rotate backups using hard links feature
#

# includes
. common_f

check_config_arg "$1"
source "$1"
check_config_opts

if [[ -d "$DEST_PATH"/daily.6 ]]; then
    rm -rf "$DEST_PATH"/daily.6
    rm "$DEST_PATH"/daily.6.log
fi

for ((i=5; i>=1; i--)); do
    DAY=$i
    NEXT=$(($DAY + 1))

    if [[ -d "$DEST_PATH"/daily."$DAY" ]]; then

        mv "$DEST_PATH"/daily."$DAY" "$DEST_PATH"/daily."$NEXT"

        # move logfile
        mv "$DEST_PATH"/daily."$DAY".log "$DEST_PATH"/daily."$NEXT".log
    fi
done

cp -al "$DEST_PATH"/daily.0 "$DEST_PATH"/daily.1
mv "$DEST_PATH"/daily.0.log "$DEST_PATH"/daily.1.log
